apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: app-container
        image: seyma1km/php-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  type: NodePort
  selector:
    app: php-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007