# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: mypool
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'seyma1km/php-project'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
